### ISSUE TITLE
[Question] CUDA out of memory | actor died unexpectedly

### ISSUE THREAD

**Issue by wangyan-hlab** [columbia-ai-robotics/scalingup#2]
Hi,

Thank you for your amazing work! 
I am following your guide to try to reproduce your work on my workstation but have met some issues:

**1. CUDA out of memory in training**
After running data generation (I chose the bin_transport task), I tried the command `python scalingup/train.py dataset_path=/path/to/drawer/dataset evaluation=bin_transport_test algo=diffusion_default` to run the training. 

However, I kept meeting the **CUDA out of memory** error. 

My device:
_Workstation:_ Dell Precision-3640-Tower
_Processor:_ Intel® Core™ i5-10500 CPU @ 3.10GHz × 12
_GPU:_ NVIDIA GeForce RTX 3090

I think you mentioned that you have tested on a RTX 3090 GPU, so I wonder if you have ever met the same issue and got any idea on it.

**2. actor died unexpectedly**
In the data generation stage, I sometimes met the **actor died unexpectedly**. I believe it is related to Ray, but unfortunately I haven't found a way to solve it. So I am turning to you for help.

I am sorry that I haven't got much experience in this field. I would really appreciate it if you may kindly give me some advice.

Best regards
Yan

**Comment by huy-ha** [comment]
Hi Yan!

Thanks for the kind words and for your interest in our work!

For the CUDA issue, you can use a smaller batch size. Although I've tested on multiple GPUs, the results in the paper (and the hyperparameters in the yaml files) are from experiments ran on A6000s. A batch size of 1024 uses 49GB on the A6000s, so I think 512 might fit and 256 will definitely fit on the 3090. The argument to add is `algo.replay_buffer.batch_size`, so the command is
```sh
python scalingup/train.py dataset_path=/path/to/drawer/dataset evaluation=bin_transport_test algo=diffusion_default algo.replay_buffer.batch_size=512
```

For the data generation, ray actors could crash due to many reasons. Here's my recommended steps for debugging:
1. Start by running the [examples](https://github.com/columbia-ai-robotics/scalingup/tree/master/examples) in the [walkthrough](https://github.com/columbia-ai-robotics/scalingup/blob/master/docs/walkthrough.md) tutorial. These examples should run the basic data generation in a single process without using ray. 
2. If these examples run fine, the next thing you could try is to use ray with one process in local mode, so ray will run all tasks and actors synchronously in the same process, allowing the default python exception handler to raise errors and print tracebacks. Concretely, this means setting `local_mode=True` in the `ray.init()` call in the [evaluation class](https://github.com/columbia-ai-robotics/scalingup/blob/master/scalingup/evaluation/base.py#L349).
3. If this runs fine, you can try running ray, but with `local_mode=False` and `log_to_driver=True` but use only one process by passing in `num_processes=1` in the python command (e.g., `python scalingup/inference.py num_processes=1 ...`).

These steps should give you some more information into why actors are dying. The most common reason in my experience is due to RAM/shared memory usage. You can use less RAM by using less processes (set `num_processes`).

Hope this helps points you in the right direction!

**Comment by wangyan-hlab** [comment]
Hi, Huy!

Thank you very much for your help! I tried to reduce the batch size to 256 and it worked well (though 512 still not fit). 

For the ray actor crash issue, actually I haven't met it on my workstation but in a virtual machine on my laptop. I followed your advice by set ```num_processes=1```, but it ran really slow so I gave up :smile: (Maybe I shouldn't have used a laptop).

BTW, I met a **new issue** in the data generation process here:
>[2023-08-07 18:10:50,263 E 138886 139173] gcs_rpc_client.h:547: Failed to connect to GCS within 60 seconds. GCS may have been killed. It's either GCS is terminated by `ray stop` or is killed unexpectedly. If it is killed unexpectedly, see the log file gcs_server.out. https://docs.ray.io/en/master/ray-observability/ray-logging.html#logging-directory-structure. The program will terminate.

It happened a few minutes after I turned off the screen (I think it didn't enter the sleep mode). Have you got any idea on it? 

Thanks again for your kind help and advice!

Best regards

**Comment by huy-ha** [comment]
I haven't come across that issue before. What does GCS's log file say?

**Comment by frrobot-ai** [comment]
> I haven't come across that issue before. What does GCS's log file say?

Hi,

Unfortunately, I met a 404 error when opening this link:
https://docs.ray.io/en/master/ray-observability/ray-logging.html#logging-directory-structure,
so I have no idea what happened exactly.

Anyway, I will just put it aside and keep on the reproduction work. 
If everything else works well, I would like to walk back and try to figure out this issue.
Thank you very much! 😸

**Comment by wangyan-hlab** [comment]
> I haven't come across that issue before. What does GCS's log file say?

Hi,

Unfortunately, I met a 404 error when opening this link:
https://docs.ray.io/en/master/ray-observability/ray-logging.html#logging-directory-structure,
so I have no idea what happened exactly.

Anyway, I will just put it aside and keep on the reproduction work.
If everything else works well, I would like to walk back and try to figure out this issue.
Thank you very much! 😸
